# number of tables is implicit
max_group_size:                    8

# location of directories and files
data_directory:                    C:\DocumentsOliverWyman\Table_Arrangements_Optimization\data_and_log_files

# names of files in the data_directory
## input
attendee_file_name:                attendees.csv

## output files
log_file_name:                     log.txt
table_assignments_file_name:       table_assignments.csv
table_summary_statistics:          table_summary.csv

# Fields
id_field_name:                     ID
name_field_name:                   Name
attribute_field_names:             [Office,Role,Start_Class,Gender]

# Score parameters
default_quadratic_penalty:         1
override_quadratic_penalty:        {Role: 2}

default_sameness_score:           0


# Format for overrides is a list of:  [attribute_name_1, specific attribute, attribute_name_2, specific attribute, override score]
#  NOTE: If no override is needed, then use the folling line:
# override_sameness_score:          []

# Princeton has only 3 attendees, all SPC and no partners
#   So want to try to have the Princeton attendees sit with a partner
override_sameness_score:          [[Role,PTR,Office,Princeton,-1]]

# Technical parameters
max_run_time_seconds:              30
max_iterations:                    400
